### ISSUE TITLE
Blog: Refactor type styles

### ISSUE THREAD

**Issue by jeremypbeasley** [jeremypbeasley/realescape#13]
CSS Styles specific to a container that's used in `default.html` and `blog.html`

Support as many of these styles as makes sense.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by jennminerva** [comment]
Got details from Jeremy and should have this done over the next week. Excited to contribute to the project :)

**Comment by kimerrikin** [comment]
Hey off-Twitter @jennminerva! Stoked to have you contributing, too! 

Can I get an update on this? Just trying to plan the release of the digital version of our annual report
 (which is dependent on this)—and where it fits in our communication plan for the end of the year. 

Not a huge rush, but definitely need to release in the next couple weeks. 

Gracias!

**Comment by jennminerva** [comment]
Hey! No problem; sorry I didn’t keep you informed. The actual text styles are fixed, but a footer bug was magically created in the process. I have tomorrow set aside to get that taken care of, so as long as there are no other hitches, I should have code to Jeremy for approval by Wednesday.

**Comment by jeremypbeasley** [comment]
First iteration complete! 

https://iwantrest.com/annual-report/

Kim, I also cleaned up the actual markdown to reflect proper formatting, separate from visual representation. Check it out and file bugs for oddities you found or want changed.

**Comment by kimerrikin** [comment]
@jeremypbeasley @jennminerva - Thank you! This looks great. Hopefully I'll have time to fill it in the rest of the way today!
