### ISSUE TITLE
Temporary Donation Page - eTap

### ISSUE THREAD

**Issue by kimerrikin** [jeremypbeasley/realescape#28]
Here's a link to the temporary eTap donation form: https://app.etapestry.com/onlineforms/REST/donateform.html

Amanda mentioned that she texted you about having our normal page up by the time the BBC story airs on Saturday?

**Comment by kimerrikin** [comment]
Fun fact: The BBC story just got pushed, so we have _at least_ until next week—we don't have a solid date.

**Comment by jeremypbeasley** [comment]
This is actually a good thing, for me at least. I'm going to continue working on the donate page tomorrow but promising Amanda it would be up by Sat was really difficult. 

In the meantime, can you cut back on those fields? We don't collect physical address with Stripe. Phone shouldn't be required either. Why email twice? You get my drift. I'm setting up the redirect now.

**Comment by jeremypbeasley** [comment]
Ok. this is all set to point to eTap until what will be https://donate.iwantrest.com is up and running.

http://iwantrest.com/donate
