### ISSUE TITLE
Jobs: Add back job listing function

### ISSUE THREAD

**Issue by kimerrikin** [jeremypbeasley/realescape#31]
We have a position we need to list ASAP.

**Comment by jeremypbeasley** [comment]
This is enabled now. It's super basic until you tell me you need more :) 

Title, short description, links to a PDF if you provide it. 

Check the copy at the bottom of the page to make sure you want to say that. "If you’re interested in working with REST, but don’t see what you’re looking for, please email us at info@iwantrest.com."

[iwantrest.com/jobs](http://iwantrest.com/jobs)
