### ISSUE TITLE
Fix "Next Training" redirect

### ISSUE THREAD

**Issue by kimerrikin** [jeremypbeasley/realescape#37]
Below "Attend a Training" on **https://iwantrest.com/volunteer/** the link is broken. I don't seem to have access to fix that. Can you do that real quick? We have a training coming up this month.

**Comment by jeremypbeasley** [comment]
This is fixed. All content on /volunteer is now dynamic and editable.

In the future, we can make this smart and automagically know the next soonest event that is a training. For now, you can go in and paste the url manually.
