### ISSUE TITLE
Re-enable Stripe /donate functionality

### ISSUE THREAD

**Issue by jeremypbeasley** [jeremypbeasley/realescape#8]

**Comment by jeremypbeasley** [comment]
This will likely borrow from the infrastructure build for `canlis_stripe`

**Comment by kimerrikin** [comment]
@jeremypbeasley here's a link to the temporary eTap donation form: https://app.etapestry.com/onlineforms/REST/donateform.html

Amanda mentioned that she texted you about having our normal page up by the time the BBC story airs on Saturday?

**Comment by jeremypbeasley** [comment]
Almost hit the finish line tonight but not quite. Still got some testing to do to make sure we can accept American Express donations. 

It's lookin good though!

<img width="1907" alt="screen shot 2017-11-14 at 11 18 40 pm" src="https://user-images.githubusercontent.com/5099620/32823497-48b029a2-c992-11e7-8b0b-82d57fc80b53.png">

**Comment by kimerrikin** [comment]
Awesome. Looks great. 

It will have monthly giving ability, yeah?

**Comment by jeremypbeasley** [comment]
I'll add that iteratively. Wanna get the basic giving back up and running asap. 

Can you provide some data-oriented insight on how valuable that is? How often is it used? What's the case to have it vs. not?

**Comment by kimerrikin** [comment]
I'll see if I can get some hard data for you. 

Right now I can tell you that it's about to be a major push for us to get sustainable/repeating donors in. We're tentatively planning on pushing it for our EOY giving campaign, which will run next month—though we don't have a certain plan for it yet.

**Comment by jeremypbeasley** [comment]
Cool. It won't be a monstrous effort to add. I'm just trying to not conflate as many things as possible and deliver value as quickly as possible. About to wrap up the basic donate functionality.

**Comment by jeremypbeasley** [comment]
Hooray!

We're up. 

The donate page is live at https://realescapedonate.herokuapp.com/, within the next 24 hours we should see donate.iwantrest.com pointing here but we can't change the link on iwantrest.com until this is validated. It's called "domain propagation" and it just takes time, unfortunately there's nothing I can do to speed it up. 

Go ahead and play with the form, enter 4242424242424242 as the CC and it'll validate with any dates. It's pointing at my personal stripe account at the moment in test mode. Try to break it! Now's the time to do so :)

I'm happy to explain it more when we talk next but for all intents and purposes the donate page is an entirely separate website. It's a separate project in github too! I've sent you an invite to collaborate. This is necessary to collect payment securely and continue to enable you to easily publish content without jumping through any hoops.

If it's not a giant pain, anything related to this donate page from here out should be captured in the "Issues" portion of `realescape_donate` and no longer on this repo.

I'm making a separate issue to point /donate and any visible links on iwantrest.com to donate.iwantrest.com now
